stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

image: maven:3.9.4-eclipse-temurin-21

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mkdir -p ~/.m2
    - |
      cat > ~/.m2/settings.xml <<EOF
      <settings>
      <servers>
      <server>
      <id>artifactory</id>
      <username>${ARTIFACTORY_LOGIN}</username>
      <password>${ARTIFACTORY_PASSWORD}</password>
      </server>
      </servers>
      </settings>
      EOF

    - mvn $MAVEN_CLI_OPTS compile
    - mvn $MAVEN_CLI_OPTS verify -l test.log
    - if [[ $CI_COMMIT_REF_PROTECTED == "true" ]]; then
        mvn $MAVEN_CLI_OPTS deploy -DaltDeploymentRepository=artifactory::default::${ARTIFACTORY_URL} -DskipTests
      fi

  artifacts:
    when: always
    paths:
      - test.log
      - target/*.jar

